version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anki_deutsch
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  bot:
    build: .
    container_name: anki_deutsch_bot
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      TELEGRAM_BOT_TOKEN: "7153540867:AAEK6o8ZLYDjY4yBM7LQtc3AnfR2pIYymuM"
      DATABASE_URL: "postgres://admin:password@postgres_db:5432/anki_deutsch?sslmode=disable"
      REDIS_URL: "redis://redis_cache:6379"
    volumes:
      - .:/app

volumes:
  pg_data:
